### ISSUE TITLE
Add ability to deprecate templates

### ISSUE THREAD

**Issue by nikku** [bpmn-io/element-templates#5]
__Is your feature request related to a problem? Please describe__

Over time templates evolve, and deprecate to make room for new templates. In C8 SaaS we [have the first of such cases](https://github.com/camunda/web-modeler/pull/2352) with more to follow.

As a user I want to have a clear path to deprecate my templates (for new ones).

__Describe the solution you'd like__

* [x] Be able to mark a template as deprecated (https://github.com/camunda/element-templates-json-schema/issues/70)
* [x] Hiding it from relevant choosers (https://github.com/bpmn-io/bpmn-js-properties-panel/issues/764)
* [x] Show deprecation hint visually in the UI (https://github.com/bpmn-io/bpmn-js-element-templates/issues/11)
* [x] No explict upgrade is suggested

__Describe alternatives you've considered__

Accept stuff like [this](https://github.com/camunda/web-modeler/pull/2352#issuecomment-1246866066) in our UI. 

__Additional context__

Came up in the context of connectors, specifically https://github.com/camunda/web-modeler/pull/2352.

See also https://github.com/camunda/web-modeler/pull/2352#issuecomment-1247091585.

**Comment by nikku** [comment]
CC @christian-konrad

**Comment by PreetiNirwal** [comment]
For option 2, would be great if we could use the same verbiage as what we've published in docs: https://docs.camunda.io/docs/next/components/modeler/desktop-modeler/element-templates/using-templates/#replacing-templates

Eg "Replace with new template"

If we can name the name template in the description even better. Eg "Replace with 'REST Connector' template"

**Comment by nikku** [comment]
Option 2 allows you to pick an arbitrary message, so that is supported, too!

**Comment by tmetzke** [comment]
Option 2 would definitely be nice, I would prefer that. But I would also be fine with Option 1 for now, given the time constraints. Depends on how much more work Option 2 is, I think.

@PreetiNirwal, maybe I got you wrong. But with Option 2 we can write whatever message we want, I think.

**Comment by PreetiNirwal** [comment]
Ok perfect on option 2. 
Agreed with Tobias:

- Option 2 preferred 
- Option 1 if option 2 will take long to implement

Thanks @nikku.

**Comment by nikku** [comment]
I'm preparing option 1 immediately and have to hand over option 2 to the team. Depends on the teams availability in the last days of September.

**Comment by marstamm** [comment]
RE Option 2:
We already support doc-refs and descriptions for normal templates. As the user needs to edit the template for deprecation anyway, could we simply re-use these fields?

**Comment by nikku** [comment]
> could we simply re-use these fields?

The idea is to be able to specify dedicated refs to migration hints. I'd not mix that with the existing documentation ref. Or do I miss something @marstamm

**Comment by barmac** [comment]
+1 for option 1 now, and option 2 as a following improvement.

**Comment by nikku** [comment]
Broke down + created individual work items.

**Comment by nikku** [comment]
Basic version pending review: https://github.com/bpmn-io/bpmn-js-properties-panel/pull/766.

**Comment by christian-konrad** [comment]
Thanks for covering this! Great to start with option 1.

**Comment by nikku** [comment]
This is long implemented (for C8, with potential to re-use across other providers).
